<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerMcOp2Ix\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMcOp2Ix/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMcOp2Ix.legacy');
=======
if (\class_exists(\ContainerPGxCuMk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGxCuMk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGxCuMk.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerMcOp2Ix\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

<<<<<<< Updated upstream
return new \ContainerMcOp2Ix\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'McOp2Ix',
    'container.build_id' => 'ed200337',
    'container.build_time' => 1584535554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMcOp2Ix');
=======
return new \Container9AICkED\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9AICkED',
    'container.build_id' => 'fc4ad45a',
    'container.build_time' => 1584538788,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9AICkED');
>>>>>>> Stashed changes
=======
    \class_alias(\ContainerPGxCuMk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPGxCuMk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PGxCuMk',
    'container.build_id' => '226381f4',
    'container.build_time' => 1584540399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGxCuMk');
>>>>>>> Stashed changes
