<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYIkkzPX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYIkkzPX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYIkkzPX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYIkkzPX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYIkkzPX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YIkkzPX',
    'container.build_id' => '3e211147',
    'container.build_time' => 1584605197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYIkkzPX');
